// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:BloodDonationAndHEalthCare/DAL/Migrations/202312281551412_donationadd.Designer.cs
    public sealed partial class donationadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(donationadd));
        
        string IMigrationMetadata.Id
        {
            get { return "202312281551412_donationadd"; }
========
    public sealed partial class postEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202312281014264_postEntity"; }
>>>>>>>> 28f43027efb55e916f52aedf5d7dd16365682d59:BloodDonationAndHEalthCare/DAL/Migrations/202312281014264_postEntity.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
