// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class postService : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postService));
        
        string IMigrationMetadata.Id
        {
<<<<<<<< HEAD:BloodDonationAndHEalthCare/DAL/Migrations/202312290305437_postService.Designer.cs
            get { return "202312290305437_postService"; }
========
            get { return "202312290215102_ok"; }
>>>>>>>> 08eca8d5d2bd9d9146729129be0f33bc28d9b71c:BloodDonationAndHEalthCare/DAL/Migrations/202312290215102_ok.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
